name: Daily NBA Update

on:
  schedule:
    - cron: '0 14 * * *'  # Daily at 9:00 AM EST (14:00 UTC)
  workflow_dispatch:  # Allows manual run

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nba_api google-api-python-client pandas

      - name: Create credentials
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Run NBA tracker
        run: python nba_tracker.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
